### ISSUE TITLE
ImportError: cannot import name _produce_migration_diffs

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio-upgrader#3]
Invenio upgrader will fail with alembic latest version (0.8.1) due to an internal change in alembic:

``` python
/home/skaplun/.virtualenvs/labs/src/invenio/invenio/modules/upgrader/operations.py in <module>()
     27 from alembic.environment import EnvironmentContext
     28 from alembic.operations import Operations
---> 29 from alembic.autogenerate.api import _produce_migration_diffs
     30 from alembic.config import Config
     31 from invenio.ext.sqlalchemy import db

ImportError: cannot import name _produce_migration_diffs
```

Due to their internal ticket 302.

**Comment by tiborsimko** [comment]
Wasn't this fixed by f90ac6160f3fd61b0b942a424937e028522e1b7c already?

**Comment by kaplun** [comment]
In invenio-upgrader yes, but it wasn't fixed in invenio versions before invenio-upgrader was factored out. So when I opened the ticket (which actually was on invenio pre-invenio-upgrader-split) I did it on invenio-upgrader... 

Hopefully these intricacies due to pre and post module split are going to disappear with 2.2

**Comment by tiborsimko** [comment]
> In invenio-upgrader yes, but it wasn't fixed in invenio versions before invenio-upgrader was factored out. 

OK, I was probably mislead by the ticket opening date that was just 4 days ago.

> Hopefully these intricacies due to pre and post module split are going to disappear with 2.2

Once we factor out the very basic modules (`invenio-base`, `invenio-utils` and friends), the dependencies will get clearer.  Until then, we'll probably repeat a few release sprints like the one of this week...
